### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by Brennall** [ladallyn/StarsWithoutNumbers-UniverseGenerator#1]
Ethnicity Generator per system

System Ethnicity Chart (A)

01-50% - Primary Ethnicity
51-76% - Secondary Ethnicity
77-82% - Tertiary Ethnicity
83-88% - Tertiary Ethnicity
89-94% - Tertiary Ethnicity
95-100% - Tertiary Ethnicity

Sector Ethnicity Chart (B)

01-50% European
51-76% Asian
77-82% South American
82-88% African
88-94% North American
95-100% Australasian - Oceanic

European breaks down into
Western European - French, English, Irish, Scottish
Eastern European - Polish, Russian, Romanian
North European - German, Danish, Swedish, Norwegian, Finnish
South European - Spanish, Portugese, Italian, Greek

Asian breaks down into
India, China, Japan

Etc

The basic aim is to fill chart A with the random generation of ethnicity from Sector Chart (B)

Roll percentage dice (d100) on Chart B and put the result into the first slot on Chart A
Then remove the entry from Chart B recalculate the size of the dice roll and repeat the procedure.

Example

We are looking at the ethnic origins of people from System 0104 Athnetia 
Roll d100 and get 69%, this is Asian.
So the first entry on Chart A is now Asian.
Asian is now removed from Chart B and it becomes as follows: -

01-50% European
51-56% South American
57-62% African
63-68% North American
69-74% Australasian - Oceanic

The next roll on this chart will use d74

The beginning of Chart A now looks like this

01-50% Asian (Primary Ethnicity)

We continue and roll d74 and get 42 which means European

So Chart A now looks like this

01-50% Asian (Primary Ethnicity)
51-76% European (Secondary Ethnicity)

Chart B now has European Removed and uses d24

01-06% South American
07-12% African
13-18% North American
19-24% Australasian - Oceanic

We roll the dice and get an 8, African.

So Chart A now looks like this

01-50% Asian (Primary Ethnicity)
51-76% European (Secondary Ethnicity)
77-82% African (Tertiary Ethnicity)

The procedure repeats till all options are full and the chart ends up looking like this

01-50% Asian (Primary Ethnicity)
51-76% European (Secondary Ethnicity)
77-82% African (Tertiary Ethnicity)
82-88% - North American (Tertiary Ethnicity)
89-94% - South American (Tertiary Ethnicity)
96-100% -  Australasian - Oceanic (Tertiary Ethnicity)

This chart represents the ethnicity of any random person from the System Athnetia 

Most of the people in the system are of Asian origin (Indian, Chinese or Japanese for example), with a significant proportion of Europeans and trace amounts of others.

This procedure would be based on the system seed, guaranteeing the same results each time.

It would be run every time a system was generated and added to the XML output.

**Comment by ladallyn** [comment]
Added
